# Generated by Django 3.0.5 on 2020-08-03 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
