# Generated by Django 3.0.5 on 2020-05-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_course_course_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentqa',
            name='body',
            field=models.TextField(),
        ),
    ]
